---

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Stop service
  ansible.builtin.service:
    name: glance
    enabled: true
    state: stopped
  when: ansible_facts['services']['glance.service']['status'] | default('not-found') != 'not-found'
  become: true

- name: Install Glance
  become: true
  block:
    - name: Create install folder
      ansible.builtin.file:
        path: '{{ glance_install_folder }}'
        state: directory
        owner: root
        group: root
        mode: '0770'
        recurse: true

    - name: Get latest release from Github
      ansible.builtin.unarchive:
        src: 'https://github.com/glanceapp/glance/releases/download/v{{ latest_release }}/glance-linux-amd64.tar.gz'
        dest: '{{ glance_install_folder }}'
        owner: root
        group: root
        remote_src: true

    - name: Create service
      ansible.builtin.template:
        src: glance.service.j2
        dest: '/etc/systemd/system/glance.service'
        owner: root
        group: root
        mode: '0755'

    - name: Start service
      ansible.builtin.systemd_service:
        name: glance
        enabled: true
        daemon_reload: true
        state: started

    - name: Save current version to file
      ansible.builtin.blockinfile:
        path: '{{ glance_version_file }}'
        create: true
        mode: '0744'
        block: |
          {{ latest_release }}
