---


- name: Create dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'
    recurse: true
  loop:
    - '{{ docker_container_config_folder }}/dumbterm/config'
    - '{{ docker_container_data_folder }}/dumbterm/data'
    - '/home/{{ default_user }}/docker/dumbterm/'

- name: Create config dir
  ansible.builtin.file:
    path: '/home/{{ default_user }}/docker/dumbterm/'
    state: directory
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'
    recurse: true

- name: Create compose file
  ansible.builtin.template:
    src: docker02/dumbterm.yml.j2
    dest: '/home/{{ default_user }}/docker/dumbterm/docker-compose.yml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/dumbterm/'
