---

- name: Create dirs
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default(default_user) }}'
    group: '{{ item.group | default(default_user) }}'
    mode: '{{ item.mode | default("0755") }}'
    recurse: true
  loop:
    - path: '{{ docker_container_config_folder }}/dumbterm/config'
      owner: root
      group: root
      mode: '0750'
    - path: '{{ docker_container_config_folder }}/dumbterm/ssh'
      owner: root
      group: root
      mode: '0600'
    - path: '{{ docker_container_data_folder }}/dumbterm/data'
    - path: '/home/{{ default_user }}/docker/dumbterm/'
  become: true

- name: Create compose file
  ansible.builtin.template:
    src: docker02/dumbterm.yml.j2
    dest: '/home/{{ default_user }}/docker/dumbterm/docker-compose.yml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/dumbterm/'
