---

ntfy_config_file: "{{ ntfy_dirs_config }}/server.yml"
ntfy_auth_file: "{{ ntfy_dirs_data }}/user.db"

ntfy_dirs_attachment: "{{ ntfy_dirs_cache }}/attachments"
ntfy_dirs_cache: /var/cache/ntfy
ntfy_dirs_config: /etc/ntfy
ntfy_dirs_data: /var/lib/ntfy
ntfy_dirs_installation: /usr/bin
ntfy_dirs_tmp: /tmp/ntfy

ntfy_system_group: ntfy
ntfy_system_user: ntfy

ntfy_url: https://ntfy.berger-em.net

ntfy_admin_user: "{{ default_user }}"
ntfy_admin_password: '{{ lookup("community.general.onepassword", "Ntfy", vault="HomeLab") }}'

ntfy_users:
  - '{ "user": "ansible", "password": {{ lookup("community.general.onepassword", "Ntfy", field="Ansible Password", vault="HomeLab") }} }'
  - '{ "user": "suki", "password": {{ lookup("community.general.onepassword", "Ntfy", field="Suki Password", vault="HomeLab") }} }'
  - '{ "user": "proxmox", "password": {{ lookup("community.general.onepassword", "Ntfy", field="Proxmox Password", vault="HomeLab") }} }'
  - '{ "user": "kuma", "password": {{ lookup("community.general.onepassword", "Ntfy", field="Kuma Password", vault="HomeLab") }} }'
  - '{ "user": "changes", "password": {{ lookup("community.general.onepassword", "Ntfy", field="Changes Password", vault="HomeLab") }} }'

# Permissions:
# read-write (alias: rw)
# read-only (aliases: read, ro)
# write-only (aliases: write, wo)
# deny (alias: none
ntfy_user_access:
  - '{ "user": "ansible", "topic": "ansible", "permission": "wo" }'
  - '{ "user": "suki", "topic": "alerts", "permission": "wo" }'
  - '{ "user": "suki", "topic": "watchtower", "permission": "wo" }'
  - '{ "user": "proxmox", "topic": "alerts", "permission": "wo" }'
  - '{ "user": "proxmox", "topic": "proxmox", "permission": "wo" }'
  - '{ "user": "kuma", "topic": "kuma", "permission": "wo" }'
  - '{ "user": "changes", "topic": "changedetection", "permission": "rw" }'
