---

# creates and starts containers from container vars with host vars defaults
- name: Configure containers
  hosts: proxmox_all_lxc
  gather_facts: false

  tasks:

    - name: Ansible Ping server
      ansible.builtin.ping:
      ignore_unreachable: true
      ignore_errors: true
      register: pingtest
      tags:
        - always

    - name: Clear host errors
      ansible.builtin.meta: clear_host_errors
      tags:
        - always

    - name: "Set ansible_user to {{ bootstrap_user }}"
      ansible.builtin.set_fact:
        ansible_user: "{{ bootstrap_user }}"
      when: pingtest.failed | default(pingtest.unreachable) | default(false)
      tags:
        - always

    - name: Install basic packages
      ansible.builtin.apt:
        pkg:
          - sudo
          - expect
          - git
          - curl
          - vim
        state: present
        update_cache: true
      become: true

    - name: Create default user
      ansible.builtin.include_role:
        name: users
      tags:
        - user

    - name: Collect facts
      ansible.builtin.setup:
      tags:
        - always

    - name: "Set ansible_user to {{ default_user }}"
      ansible.builtin.set_fact:
        ansible_user: "{{ default_user }}"
      when: pingtest.failed | default(pingtest.unreachable) | default(false)

    - name: Update ssh config
      ansible.builtin.include_role:
        name: lxc_config
      tags:
        - lxc_config

    - name: Configure/Install Checkmk
      ansible.builtin.include_tasks: tasks/checkmk.yml
      tags:
        - checkmk

    - name: Configure/Install Docker
      when: inventory_hostname is match('.*(docker|gitea|authentik|kestra|nextcloud).*')
      tags:
        - docker
      block:
        - name: Install Docker
          ansible.builtin.include_role:
            name: docker

        - name: Deploy host container
          ansible.builtin.include_tasks: 'tasks/{{ inventory_hostname }}/main.yml'
          when: inventory_hostname != 'authentik'
          tags:
            - docker.deploy

    - name: 'Configure/Install role based container'
      ansible.builtin.include_tasks: tasks/lxc_config.yml
      vars:
        container: '{{ lxc }}'
      loop:
        - name: adguard
          role: adguard_home
          search: dns
        - name: actualbudget
        - name: glance
        - name: semaphore
        - name: ntfy
        - name: caddy
        - name: uptimekuma
        - name: grafana
        - name: forgejo
      loop_control:
        loop_var: lxc

    - name: Configure/Install task based container
      ansible.builtin.include_tasks: 'tasks/{{ inventory_hostname }}.yml'
      when: inventory_hostname is match('.*(authentik).*')

    - name: Do OS update
      ansible.builtin.include_tasks: tasks/os_update.yml
      when:
        - '"semaphore" not in inventory_hostname'
      tags:
        - os_update
