---

collections:
  # Basic ansible community modules
  - name: checkmk.general
  - name: community.crypto
  - name: community.docker
  - name: community.general
  - name: community.grafana
  - name: grafana.grafana
  - name: onepassword.connect
  - name: prometheus.prometheus
  - name: serverscom.mitogen
