---

- name: Create LXC Container
  run_once: true
  delegate_to: localhost
  block:
    - name: Get all defined hosts
      ansible.builtin.find:
        paths: "./host_vars"
        patterns: "*.yml"
      register: defined_hosts

    - name: Get vars from file
      ansible.builtin.set_fact:
        host_vars_list: "{{ host_vars_list | default([]) + [lookup('ansible.builtin.file', item.path) | from_yaml] }}"
      loop: "{{ defined_hosts.files }}"

    - name: Create missing LXC container
      community.general.proxmox:
        api_host: '{{ pve_api_host }}'
        api_port: '{{ pve_api_port }}'
        api_user: '{{ pve_apiuser }}'
        api_password: '{{ pve_root_password }}'
        state: 'present'

        hostname: '{{ item.host_name }}'
        cores: '{{ vhost.cores }}'
        description: '{{ vhost.description }}'
        disk: '{{ vhost.disk }}'
        features: '{{ vhost.features }}'
        force: '{{ vhost.force }}'
        memory: '{{ vhost.memory }}'
        netif:
          net0: "name=eth0,gw={{ item.host_gateway }},ip={{ item.host_ip }}{{ item.host_subnet }},bridge=vmbr0,firewall=0,tag={{ item.host_vlan }}"
        node: '{{ vhost.node }}'
        onboot: '{{ vhost.onboot }}'
        ostemplate: '{{ vhost.ostemplate }}'
        password: '{{ vhost.password }}'
        swap: '{{ vhost.swap }}'
        tags: '{{ vhost.tags }}'
        vmid: '{{ vhost.vmid }}'
      vars:
        vhost: "{{ pve_lxc_defaults | combine(item.lxc_data, recursive=True, list_merge='replace') }}"
      loop: '{{ host_vars_list }}'
      timeout: 60
      loop_control:
        label: "{{ item.host_name }}"
        pause: 2
      notify:
        - Sleep
      register: 'created_lxc_container'
      when: 'item.host_name not in groups["proxmox_all_lxc"]'

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Set facts
      ansible.builtin.set_fact:
        created_hosts: '{{ created_hosts | combine({item.item.host_name: {"node": item.vhost.node, "vmid": item.vhost.vmid}}) }}'
      with_items: '{{ created_lxc_container.results }}'
      when: item.changed # noqa: no-handler

    - name: Start container
      community.general.proxmox:
        api_host: '{{ pve_api_host }}'
        api_port: '{{ pve_api_port }}'
        api_user: '{{ pve_apiuser }}'
        api_password: '{{ pve_root_password }}'

        node: '{{ item.value.node | default(pve_lxc_defaults.node) }}'
        hostname: '{{ item.key }}'
        state: started
      with_dict: '{{ created_hosts }}'
      notify:
        - Sleep

    - name: Enable root ssh in container
      ansible.builtin.include_tasks: configure_lxc.yml
      vars:
        lxc_node: '{{ item.value.node }}'
        lxc_id: '{{ item.value.vmid }}'
      with_dict: '{{ created_hosts }}'
