---

- name: Configure Caddy
  become: true
  block:

    - name: Remove old Caddy vhost files
      tags: caddy.vhosts
      ansible.builtin.file:
        path: "{{ caddy_config_path }}/vhosts"
        state: absent

    - name: Create vhosts directory
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: "{{ caddy_user_name }}"
        group: '{{ caddy_group_name }}'
      loop:
        - "{{ caddy_config_path }}/vhosts"

    - name: Rewrite Caddyfile
      ansible.builtin.template:
        src: Caddyfile.j2
        dest: "{{ caddy_config_path }}/Caddyfile"
        mode: "0644"
        owner: "{{ caddy_user_name }}"
        group: '{{ caddy_group_name }}'
        lstrip_blocks: true
      notify: Reload caddy

    - name: Rewrite config snippets
      ansible.builtin.template:
        mode: "0644"
        src: 'snippets/{{ item }}.j2'
        dest: "{{ caddy_config_path }}/snippets/{{ item }}"
        owner: "{{ caddy_user_name }}"
        group: '{{ caddy_group_name }}'
      loop:
        - tls.conf
        - protected.conf
        - layer4.conf
      notify: Reload caddy

    - name: Create .env file
      ansible.builtin.template:
        src: templates/dot_env.j2
        dest: '{{ caddy_config_path }}/.env'
        owner: '{{ caddy_user_name }}'
        group: '{{ caddy_group_name }}'
        mode: '0640'
      vars:
        secrets:
          - key: CLOUDFLARE_API_TOKEN
            value: '{{ lookup("community.general.onepassword", "Caddy Cloudflare Token", vault="HomeLab") }}'

    - name: Configure vhosts
      ansible.builtin.include_tasks: vhosts.yml
      tags: caddy.vhosts
      loop: "{{ groups['proxmox_all_lxc'] }}"
      loop_control:
        loop_var: lxc_host
