---

- name: Install checkmk server
  ansible.builtin.include_role:
    name: checkmk.general.server
  vars:
    checkmk_server_version: "2.4.0p2"
    checkmk_server_edition: 'cre'
    checkmk_server_cleanup: 'true'

    checkmk_server_sites:
      - name: 'homelab'
        version: "{{ checkmk_server_version }}"
        update_conflict_resolution: 'abort'
        state: 'started'
        admin_pw: '{{ lookup("community.general.onepassword", "CheckMK", vault="HomeLab") }}'
        omd_config:
          - var: AUTOSTART
            value: 'on'
  when:
    - '"checkmk" in inventory_hostname'

- name: Install checkmk agent
  ansible.builtin.include_role:
    name: checkmk.general.agent
  vars:
    checkmk_agent_version: "2.4.0p2"
    checkmk_agent_edition: 'cre'
    checkmk_agent_server_protocol: https
    checkmk_agent_server: checkmk.berger-em.net
    checkmk_agent_site: 'homelab'
    checkmk_agent_user: 'agent_registration'
    checkmk_agent_secret: '{{ lookup("community.general.onepassword", "CheckMK", field="agent password", vault="HomeLab") }}'
    checkmk_agent_auto_activate: 'true'
    checkmk_agent_force_foreign_changes: 'true'
    checkmk_agent_add_host: 'true'
    checkmk_agent_host_name: "{{ inventory_hostname }}"
    checkmk_agent_discover: 'true'
    checkmk_agent_tls: 'true'
    checkmk_agent_no_log: 'false'
    checkmk_agent_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    checkmk_agent_host_attributes:
      ipaddress: "{{ checkmk_agent_host_ip | default(omit) }}"
  when:
    - '"checkmk" not in inventory_hostname'
