---

- name: Install Go
  become: true
  block:
    - name: Check if Go is already installed.
      ansible.builtin.command:
        cmd: /usr/local/go/bin/go version
      ignore_errors: true
      register: go_version_result
      changed_when: false

    - name: Remove current installation.
      ansible.builtin.file:
        state: absent
        path: /usr/local/go
      when:
        - go_version_result is succeeded
        - go_version not in go_version_result.stdout

    - name: Get latest release from Github
      ansible.builtin.unarchive:
        src: '{{ go_download_url }}'
        dest: '/usr/local'
        mode: '0755'
        remote_src: true
      when: go_version_result is failed
            or go_version not in go_version_result.stdout

    - name: Add Go to to system-wide $PATH.
      ansible.builtin.copy:
        dest: /etc/profile.d/go-path.sh
        mode: '0755'
        content: |-
          export PATH=$PATH:/usr/local/go/bin
