---

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: apt_update
  failed_when: apt_update.rc != 0

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    only_upgrade: true
  register: apt_upgrade
  failed_when: apt_upgrade.rc != 0
  changed_when: apt_upgrade.changed

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Send a embedded message to the Discord channel
  community.general.discord:
    webhook_id: '{{ lookup("community.general.onepassword", "Discord Webhooks", section="Ansible", field="webhook_id", vault="HomeLab") }}'
    webhook_token: '{{ lookup("community.general.onepassword", "Discord Webhooks", section="Ansible", field="webhook_token", vault="HomeLab") }}'
    username: The Automater!
    embeds:
      - title: "Reboot required!"
        description: "There is a reboot required on your server!"
        fields:
          - name: server
            value: '{{ inventory_hostname }}'
        footer:
          - text: Created by Ansible
        color: "#ff0000"
        timestamp: "{{ ansible_date_time.iso8601 }}"
  when: reboot_required_file.stat.exists

# - name: Reboot server if there was a kernel update
#   ansible.builtin.reboot:
#     msg: "Rebooting server because kernel was updated"
#     connect_timeout: 5
#     reboot_timeout: 300
#     pre_reboot_delay: 0
#     post_reboot_delay: 30
#     test_command: uptime
#   when: reboot_required_file.stat.exists
