---

- name: Create dirs
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'
    recurse: true
  loop:
    - '{{ docker_container_config_folder }}/kestra/'
    - '{{ docker_container_data_folder }}/kestra/'
    - '{{ docker_container_data_folder }}/postgresql/'
    - '/home/{{ default_user }}/docker/kestra/'

- name: Create application config
  ansible.builtin.template:
    src: kestra/application.yml.j2
    dest: '{{ docker_container_config_folder }}/kestra/application.yaml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0750'

- name: Create compose file
  ansible.builtin.template:
    src: kestra/kestra_stack.yml.j2
    dest: '/home/{{ default_user }}/docker/kestra/docker-compose.yml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

- name: Run `docker compose up` again
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/kestra/'
