---

- name: Get latest release tag from Github
  when: (latest_release is not defined) or (latest_release == 'latest')
  run_once: true
  block:
    - name: Determine latest GitHub release (local)
      ansible.builtin.uri:
        url: '{{ semaphore_github_url }}'
        body_format: json
      register: _github_release
      until: _github_release.status == 200
      retries: 5

    - name: Set latest_release
      ansible.builtin.set_fact:
        latest_release: "{{ _github_release.json.tag_name
          | regex_replace('^v?(.*)$', '\\1') }}"

- name: Latest version
  ansible.builtin.debug:
    msg: "Latest version {{ latest_release }}"

- name: Check if version file exists
  ansible.builtin.stat:
    path: '{{ semaphore_version_file }}'
  register: release_file

- name: Get version file
  ansible.builtin.slurp:
    src: '{{ semaphore_version_file }}'
  register: current_release
  when: release_file.stat.exists

- name: Install Semaphore
  ansible.builtin.include_tasks: install.yml
  when: (not release_file.stat.exists) or (latest_release not in current_release['content'] | b64decode)
  tags: semaphore.setup

- name: Update configuration
  ansible.builtin.include_tasks: configure.yml
  when: not sempahore_installed is defined
  tags: semaphore.config

- name: Install modules
  ansible.builtin.include_tasks: modules.yml
  tags: semaphore.modules
