---

- name: Install modules for semaphore
  become: true
  block:
    - name: Install 1password repo
      ansible.builtin.deb822_repository:
        name: 1password
        uris: 'https://downloads.1password.com/linux/debian/amd64'
        types: deb
        suites: stable
        components: main
        signed_by: 'https://downloads.1password.com/linux/keys/1password.asc'
        state: present

    - name: Install 1password cli
      ansible.builtin.apt:
        name:
          - 1password-cli
        state: present
        update_cache: true
