---

- name: Install modules for semaphore
  become: true
  block:
    - name: Install 1password cli
      ansible.builtin.deb822_repository:
        name: docker
        uris: 'https://downloads.1password.com/linux/debian/{{ ansible_architecture | lower }}'
        types: deb
        suites: 'main'
        components: stable
        signed_by: 'https://downloads.1password.com/linux/keys/1password.asc'
        state: present

    - name: Install 1password cli
      ansible.builtin.apt:
        name:
          - 1password-cli
        state: present
        update_cache: true
