---

- name: Deploy paperless
  become: true
  block:
    - name: Create dirs
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: directory
        owner: '{{ item.owner | default(default_user) }}'
        group: '{{ item.group | default(default_user) }}'
        mode: '{{ item.mode | default("0755") }}'
        recurse: true
      loop:
        - path: '{{ docker_container_data_folder }}/paperless'
          mode: '0777'
          owner: 'root'
          group: 'root'
        - path: '/home/{{ default_user }}/docker/paperless/'
        - path: '{{ docker_container_data_folder }}/paperless/scripts/'
        - path: '{{ docker_container_data_folder }}/paperless/ai_data/'
        - path: '{{ docker_container_data_folder }}/paperless/consume/'
          group: 'ftpuser'
          mode: '0775'

    - name: Create config files
      ansible.builtin.template:
        src: 'paperless/{{ item.name }}'
        dest: '{{ item.dest_path }}/{{ item.dest_name }}'
        owner: '{{ default_user }}'
        group: '{{ default_user }}'
        mode: '0755'
      loop:
        - name: "paperless_stack.yml.j2"
          dest_name: "docker-compose.yml"
          dest_path: "/home/{{ default_user }}/docker/paperless"
        - name: "docker-compose.env.j2"
          dest_name: "docker-compose.env"
          dest_path: "/home/{{ default_user }}/docker/paperless"
        - name: "ai.env.j2"
          dest_name: "ai.env"
          dest_path: "/home/{{ default_user }}/docker/paperless/"
        - name: "post-consumption.sh.j2"
          dest_name: "post-consumption.sh"
          dest_path: "{{ docker_container_data_folder }}/paperless/scripts/"

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/paperless/'
