---

- name: Deploy Paperless-ngx
  ansible.builtin.include_tasks: install.yml
  tags:
    - paperless.setup

- name: Install ProFTPd
  ansible.builtin.include_tasks: proftp.yml
  tags:
    - paperless.ftp
