---

- name: Deploy proftpd
  become: true
  block:

    - name: Install packages
      ansible.builtin.apt:
        pkg: proftpd-basic
        state: present

    - name: Create user ftpuser
      ansible.builtin.user:
        name: ftpuser
        shell: /bin/bash
        state: present
        home: '{{ docker_container_data_folder }}/paperless/consume/'
        password: "{{ passwd_bergefe | password_hash('sha512') }}"

    - name: Change access rights
      ansible.builtin.file:
        path: '{{ docker_container_data_folder }}/paperless/consume/'
        state: directory
        owner: '{{ default_user }}'
        group: 'ftpuser'
        mode: '0775'
        recurse: true

    - name: Create config files
      ansible.builtin.template:
        src: 'paperless/{{ item.name }}'
        dest: '{{ item.dest_path }}/{{ item.dest_name }}'
        owner: 'root'
        group: 'root'
        mode: '0744'
      loop:
        - name: "proftpd.conf.j2"
          dest_name: "proftpd.conf"
          dest_path: "/etc/proftpd/"
        - name: "ftp_custom.conf.j2"
          dest_name: "custom.conf"
          dest_path: "/etc/proftpd/conf.d"

    - name: Restart proftpd
      ansible.builtin.service:
        name: proftpd
        state: restarted
