---

- name: Block for access rights
  become: true
  block:

    - name: Create the config file from template
      ansible.builtin.template:
        src: "server.yml.j2"
        dest: "{{ ntfy_config_file }}"
        owner: "{{ ntfy_system_user }}"
        group: "{{ ntfy_system_group }}"
        mode: "0600"

    - name: Restart ntfy
      ansible.builtin.systemd:
        daemon_reload: true
        name: ntfy.service
        state: restarted

    - name: Add ntfy Admin user
      ansible.builtin.shell: |
        export NTFY_PASSWORD={{ lookup("community.general.onepassword", "Ntfy", vault="HomeLab") }}
        ntfy user add --role=admin --ignore-exists {{ lookup("community.general.onepassword", "Ntfy", field="Username", vault="HomeLab") }}
        unset NTFY_PASSWORD
      changed_when: true

    - name: Add additional ntfy users
      ansible.builtin.shell: |
        export NTFY_PASSWORD={{ item.password }}
        ntfy user add --ignore-exists {{ item.user }}
        unset NTFY_PASSWORD
      changed_when: true
      loop: '{{ ntfy_users }}'

    - name: Restart ntfy
      ansible.builtin.systemd:
        daemon_reload: true
        name: ntfy.service
        state: restarted

    - name: Set user access rights
      ansible.builtin.command:
        cmd: 'ntfy access {{ item.user }} {{ item.topic }} {{ item.permission }}'
      changed_when: true
      loop: '{{ ntfy_user_access }}'
