---

forgejo_codeberg_url: https://codeberg.org/api/v1/repos/forgejo/forgejo/releases/latest

forgejo_version_file: '/home/{{ forgejo_system_user }}/forgejo.txt'

forgejo_binary_path: '/usr/local/bin/forgejo'
forgejo_work_path: '/var/lib/forgejo'
forgejo_config_path: '/etc/forgejo'

forgejo_runner_path: '{{ docker_container_data_folder }}/runner'

forgejo_system_user: git
forgejo_system_group: git

forgejo_admin_user: 'bergefe_local'
forgejo_admin_email: 'forgejo@berger-em.de'

# From 1Password
forgejo_secret_key: '{{ lookup("community.general.onepassword", "Forgejo", field="Secret Key", vault="HomeLab") }}'
forgejo_internal_token: '{{ lookup("community.general.onepassword", "Forgejo", field="Internal Token", vault="HomeLab") }}'
forgejo_oauth_jwt_secret: '{{ lookup("community.general.onepassword", "Forgejo", field="JWT Secret", vault="HomeLab") }}'
forgejo_runner_shared_secret: '{{ lookup("community.general.onepassword", "Forgejo", field="Runner Shared Secret", vault="HomeLab") }}'
