---

grafana_url: "http://192.168.1.33:3000"
grafana_user: '{{ lookup("community.general.onepassword", "Grafana", field="Username", vault="HomeLab") }}'
grafana_password: '{{ lookup("community.general.onepassword", "Grafana", vault="HomeLab") }}'
