---

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Stop service
  ansible.builtin.service:
    name: actualbudget
    enabled: true
    state: stopped
  when: ansible_facts['services']['actualbudget.service']['status'] | default('not-found') != 'not-found'
  become: true

- name: Install Actualbudget
  become: true
  block:
    - name: Install dependencies
      ansible.builtin.package:
        name:
          - tini
          - gpg
          - build-essential
          - git
          - nodejs
        update_cache: true
        state: present

    - name: Install global npm modules
      community.general.npm:
        name:
          - yarn
        global: true

    - name: Get latest release from Github
      ansible.builtin.unarchive:
        src: 'https://github.com/actualbudget/actual/archive/refs/tags/{{ latest_release }}.tar.gz'
        dest: '{{ actualbudget_install_folder }}'
        owner: root
        group: root

    - name: Create required folders
      ansible.builtin.file:
        path: '{{ actualbudget_data_folder }}/{{ item }}'
        state: directory
        owner: root
        group: root
        mode: '0755'
        recurse: true
      loop:
        - server-files
        - upload
        - migrate
        - user-files
        - migrations
        - config

    - name: Create config
      ansible.builtin.template:
        src: env.j2
        dest: '{{ actualbudget_data_folder }}/.env'
        owner: root
        group: root
        mode: '0755'

    - name: Install YARN packages
      community.general.yarn:
        path: '{{ actualbudget_install_folder }}'

    - name: Create OpenSSL Certificate
      community.crypto.x509_certificate:
        path: '{{ actualbudget_install_folder }}/selfhost.crt'
        privatekey_path: '{{ actualbudget_install_folder }}/selfhost.key'
        csr_path: '{{ actualbudget_install_folder }}/selfhost.csr'
        provider: selfsigned

    - name: Create service
      ansible.builtin.template:
        src: actualbudget.service.j2
        dest: '/etc/systemd/system/actualbudget.service'
        owner: root
        group: root
        mode: '0755'

    - name: Start service
      ansible.builtin.systemd_service:
        name: actualbudget
        enabled: true
        daemon_reload: true
        state: started

    - name: Save current version to file
      ansible.builtin.blockinfile:
        path: '{{ actualbudget_version_file }}'
        create: true
        mode: '0744'
        block: |
          {{ latest_release }}
