---

- name: Create dirs
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    owner: '{{ item.owner | default(default_user) }}'
    group: '{{ item.group | default(default_user) }}'
    mode: '{{ item.mode | default("0755") }}'
    recurse: true
  loop:
    - path: '{{ docker_container_data_folder }}/actualbudget/data'
    - path: '/home/{{ default_user }}/docker/actualbudget'
  become: true

- name: Create .env file
  ansible.builtin.template:
    src: dot_env.j2
    dest: '/home/{{ default_user }}/docker/actualbudget/.env'
    mode: '0600'
  vars:
    secrets:
      - key: ACTUAL_TRUSTED_PROXIES
        value: '[192.168.10.0/24]'
      - key: ACTUAL_OPENID_DISCOVERY_URL
        value: https://auth.berger-em.net/application/o/actual-budget/
      - key: ACTUAL_OPENID_CLIENT_ID
        value: '{{ lookup("community.general.onepassword", "ActualBudget", section="Authentik", field="client-id", vault="HomeLab") }}'
      - key: ACTUAL_OPENID_CLIENT_SECRET
        value: '{{ lookup("community.general.onepassword", "ActualBudget", section="Authentik", field="client-secret", vault="HomeLab") }}'
      - key: ACTUAL_OPENID_SERVER_HOSTNAME
        value: https://actual.berger-em.net

- name: Create compose file
  ansible.builtin.template:
    src: actualbudget.yml.j2
    dest: '/home/{{ default_user }}/docker/actualbudget/compose.yml'
    owner: '{{ default_user }}'
    group: '{{ default_user }}'
    mode: '0755'

- name: Run `docker compose up`
  community.docker.docker_compose_v2:
    project_src: '/home/{{ default_user }}/docker/actualbudget/'
    recreate: always
