---

# Baisc host settings
host_name: glance
host_ip: 192.168.1.31
host_gateway: 192.168.1.1
host_subnet: /24
host_vlan: 1

# LXC settings
lxc_data:
  vmid: 105
  node: "evoli"
  cores: 2
  memory: 2048
  disk: 'zfs:5'
  netif:
    net0: "name=eth0,gw={{ host_gateway }},ip={{ host_ip }}{{ host_subnet }},bridge=vmbr0,firewall=0,tag={{ host_vlan }}"

# Reverse Proxy settings
proxy:
  - name: '{{ host_name }}'
    hostname: 'dashboard.berger-em.net'
    proxy_host: 'http://{{ host_ip }}:8080'
