---

# Baisc host settings
host_name: jellyfin
host_ip: 192.168.20.13
host_gateway: 192.168.20.1
host_subnet: /24
host_vlan: 20

# LXC settings
lxc_data:
  vmid: 102
  node: "pikachu"
  cores: 2
  memory: 2048
  disk: 'zfs:18'
  netif:
    net0: "name=eth0,gw={{ host_gateway }},ip={{ host_ip }}{{ host_subnet }},bridge=vmbr0,firewall=0,tag={{ host_vlan }}"

# Reverse Proxy settings
proxy:
  - name: '{{ host_name }}'
    hostname: '{{ host_name }}.berger-em.net'
    proxy_host: 'http://{{ host_ip }}:8096'
    protected_enabled: false
