---

# Baisc host settings
host_name: paperless-ngx-docker
host_ip: 192.168.1.19
host_gateway: 192.168.1.1
host_subnet: /24
host_vlan: 1

# LXC settings
lxc_data:
  vmid: 109
  node: "pikachu"
  cores: 4
  memory: 4096
  disk: 'zfs:20'
  netif:
    net0: "name=eth0,gw={{ host_gateway }},ip={{ host_ip }}{{ host_subnet }},bridge=vmbr0,firewall=0,tag={{ host_vlan }}"
  tags:
    - ansible
    - docker

# Reverse Proxy settings
proxy:
  - name: 'paperless'
    hostname: 'paperless.berger-em.net'
    proxy_host: 'http://{{ host_ip }}'
    protected_private: true
    protected_internal: false
