---

# Baisc host settings
host_name: webserver
host_ip: 192.168.1.25
host_gateway: 192.168.1.1
host_subnet: /24
host_vlan: 1

# LXC settings
lxc_data:
  vmid: 113
  node: "evoli"
  cores: 1
  memory: 1024
  disk: 'zfs:5'
  netif:
    net0: "name=eth0,gw={{ host_gateway }},ip={{ host_ip }}{{ host_subnet }},bridge=vmbr0,firewall=0,tag={{ host_vlan }}"

# Reverse Proxy settings
proxy:
  - name: '{{ host_name }}'
    hostname: '{{ host_name }}.berger-em.net'
    proxy_host: 'http://{{ host_ip }}'
