---

# Role based on https://raw.githubusercontent.com/community-scripts/ProxmoxVE/main/install/adguard-install.sh

- name: Get latest release from Github
  ansible.builtin.unarchive:
    src: "{{ adguard_home_url }}"
    dest: '{{ adguard_home_install_path }}'
    owner: root
    group: root
  become: true

- name: Create service
  ansible.builtin.template:
    src: adguardhome.service.j2
    dest: '/etc/systemd/system/adguardhome.service'
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Start service
  ansible.builtin.systemd_service:
    name: adguardhome
    enabled: true
    daemon_reload: true
    state: started
  become: true

- name: Save current version to file
  ansible.builtin.blockinfile:
    path: '{{ adguard_home_version_file }}'
    create: true
    mode: '0744'
    block: |
      {{ latest_release }}
  become: true
