---

caddy_homelab_internal_ips: ["192.168.0.0/16"]
caddy_homelab_priv_ips: ["192.168.1.0/24", "192.168.10.0/24", "192.168.40.0/24", "192.168.136.0/24"]

# Vhost default values
caddy_vhost_defaults:
  template: reverse.j2
  compress: true
  proxy_host: null
  proxy_transparent_disable: false
  security_headers: false
  basicauth: false
  basicauth_path: "/"
  www_redir: false
  root: null
  php_fastcgi_enabled: null
  php_fastcgi_path: null
  responds: []
  rewrites: []
  file_server: false
  file_server_browse: false
  authentik_enabled: false
  protected_enabled: true
  protected_internal: true
  protected_private: false
  protected_remote_ips: []
  protected_header_name: null
  protected_header_value: null
  bind: null
